### ISSUE TITLE
Would be great to add a cpu's temperature icon 

### ISSUE THREAD

**Issue by benerogerio** [strayge/tray-monitor#11]
Hey! great job man! A good idea would be the possibility of showing a CPU temperature icon. It would be amazing!

**Comment by strayge** [comment]
Hi,
Unfortunately, Windows does not provide a generic way to monitor CPU temperature.

This will require:
1. Add an external dependency, such as [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)
1.1. This dependency has built-in information for sensors of different CPUs, so it will require regular updates (for new CPUs).
2. Reading those sensors directly from CPU registers require administrator privileges, which will require new way of autostart.

My goal for this icons is to work years without touching, so I don't see direct and easy way to fulfill your request.
Sorry for disappointment.

**Comment by benerogerio** [comment]
I completely understand man! Again, great job!
