### ISSUE TITLE
Microphone Input Level Icon

### ISSUE THREAD

**Issue by cpfinlay** [strayge/tray-monitor#2]
I use all of your notification icon (purchased via Microsoft store). Is it possible to create a similar program to show input volume from a microhome?  Not the setting; more like a miniature VU Meter.

**Comment by strayge** [comment]
@cpfinlay try it https://www.microsoft.com/store/apps/9NJ372WTD1K5

**Comment by cpfinlay** [comment]
It works!!  Thank you!!!!  🙂
________________________________

**Comment by cpfinlay** [comment]
I get an occasional .NET error and it stops.  Just an FYI. If you want me to provide any information from my PC, please let me know!
________________________________

**Comment by strayge** [comment]
1. got text/screenshot of error?
2. something specific action at error? plug/unplug micro/audio devices?
3. how long it works until error?
4. win10?

**Comment by cpfinlay** [comment]
1.  I am waiting for the error to recur. I will send that when I see it again. I can't seem to force it to happen. 🙁
  2.  I believe the error started after this month's Windows Security updates, but not 100% sure about that.
  3.  The tray seems to stay active about 1-2 minutes before disappearing. I am not seeing the error come back up even after it disappears.
  4.  Windows 10; all available patches applied.

Is there a Windows log or app log I can provide?
________________________________

**Comment by strayge** [comment]
i reproduced error, will fix on free time

**Comment by cpfinlay** [comment]
Understood! Glad you were able to reproduce the issue. I know that helps!! 🙂
________________________________

**Comment by cpfinlay** [comment]
Hello,

The .NET error popped up again. Here's the info if that helps any!!

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Already recording
   at NAudio.Wave.WaveInEvent.StartRecording()
   at MicIcon.CustomTrayIcon.UpdateDeviceList()
   at MicIcon.CustomTrayIcon.<.ctor>b__6_1(Object sender, EventArgs args)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MicIcon
    Assembly Version: 2.4.0.0
    Win32 Version: 2.4.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/48600strayge.MicTrayMonitor_1.0.0.0_neutral__qdcnzjp83nc4r/MicIcon/MicIcon.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NAudio.WinMM
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/48600strayge.MicTrayMonitor_1.0.0.0_neutral__qdcnzjp83nc4r/MicIcon/NAudio.WinMM.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
NAudio.Core
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/48600strayge.MicTrayMonitor_1.0.0.0_neutral__qdcnzjp83nc4r/MicIcon/NAudio.Core.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/48600strayge.MicTrayMonitor_1.0.0.0_neutral__qdcnzjp83nc4r/MicIcon/NAudio.Wasapi.DLL
----------------------------------------
NAudio.WinForms
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/48600strayge.MicTrayMonitor_1.0.0.0_neutral__qdcnzjp83nc4r/MicIcon/NAudio.WinForms.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


________________________________

**Comment by strayge** [comment]
Thanks, yep, same error as I spotted.
Fix ready, but testing today.
I'll write as upload to store.

**Comment by strayge** [comment]
update in store

**Comment by cpfinlay** [comment]
Hello again!

I had the opportunity to use it today and it did not give me the error, but it does disappear from the task bar after roughly 30 seconds. It shows up in task manager and the microphone icon remains saying it is in use by MicIcon.

Please let me know if I can be of assistance.

Thank you,
________________________________

**Comment by cpfinlay** [comment]
I upgraded to Windows 11 over the weekend and it started working consistently for me now! 🙂

Must have been something screwed up with my Windows 10 installation that the upgrade fixed.
________________________________
