### ISSUE TITLE
Trojan detected by Defender

### ISSUE THREAD

**Issue by mhabets** [strayge/tray-monitor#6]
![image](https://github.com/strayge/tray-monitor/assets/2016449/558a19cb-887f-4e08-b779-5d210a42dd2d)

**Comment by strayge** [comment]
Thanks for report.

But locally my Defender finds nothing.   
Also on [virustotal](https://www.virustotal.com/gui/file/6d76fc7f6916417aeaede2a3f960c0bc5656780fc30e4c9abeea78027ff764d2/detection) no detects by microsoft.

Have you tried update Defender via Windows Update?

**Comment by strayge** [comment]
not reproducing for me
