### ISSUE TITLE
[BUG] CPU % is more than 100%

### ISSUE THREAD

**Issue by Iz-zzzzz** [strayge/tray-monitor#9]
![image](https://github.com/strayge/tray-monitor/assets/57972212/8d537fbd-9fb6-47a2-babe-8d1adf874e97)
This always happens when PC renders a video.

**Comment by strayge** [comment]
Hi,
Sorry for delay in answer.

I have reproduced it (but for myself it was like 101-103%).
And it is exactly the numbers Windows returns as CPU utility via its API.

For me lower than 100% number looks like exactly the same as shows in Task Manager,
so I suspect Windows itself just cut high numbers down to 100%.

This is well [observed](https://stackoverflow.com/questions/74933840/processor-utility-counter-returning-over-100) behavior and possibly related with TurboBoost-like technologies when CPU overclock itself for short amount of time.

As it is not affect graph, I do not see it as a bug.
